### ISSUE TITLE
Distance_Matrix: 'Unable to find an appropriate routing profile.' - for all but 'driving-car'

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice-py#19] opened 2018-10-02 09:37 UTC
Reported by @AvePazuzu

See https://github.com/GIScience/openrouteservice/issues/299

I have been using the the function few weeks ago and it worked properly.

Since yesterday I get the titled error message for all profiles but 'driving-car'.

I have tried the examples but I always get the same result.

Here is my test code(py 3.6):

```
req_param = {'profile': 'driving-hgv', metrics' : ['duration', 'distance'], 'optimized': 'true', 'units': 'km', 'locations': [[9.970093,48.477473], [9.207916,49.153868]]}

dist_mat = clnt2.distance_matrix(**req_param)
```

And as response I get:

`ApiError: 500 ({'error': {'code': 6099, 'message': 'Unable to find an appropriate routing profile.'}, 'info': {'engine': {'version': '4.5.0', 'build_date': '2018-09-23T13:46:49Z'}, 'timestamp': 1538421210721}})`

Also, is there a lito find an mit for the number of elements of 25 now?

`ApiError: 400 ({'error': {'code': 6004, 'message': "Parameter 'sources/destinations=36' is out of range. Maximum possible value is 25."}, 'info': {'engine': {'version': '4.5.0', 'build_date': '2018-09-23T13:47:22Z'}, 'timestamp': 1538421896753}})`

Did I do something wrong here?

Many Thanks & bis dann.

**Comment by nilsnolde** [comment] 2018-10-02 12:36
Ok, true, sorry, I need to update PyPI. Pull the latest Github `master` and install via pip, so you're on version 0.4. That'll solve the 6099.
The second question: no, there is no way in ors-py to limit the input to 25. That's your job;)

**Comment by AvePazuzu** [comment] 2018-10-18 12:49
Hi nilsolde, 
sorry to bother you guys again but what is the version of the latest `master` ? I have installed what was available and my new version seems to be '4.7.0'. But still, it did not solve the problem for me. Same error with later version.
`ApiError: 500 ({'error': {'code': 6099, 'message': 'Unable to find an appropriate routing profile.'}, 'info': {'engine': {'version': '4.7.0', 'build_date': '2018-10-05T10:45:12Z'}, 'timestamp': 1539866493163}})`

**Comment by nilsnolde** [comment] 2018-10-18 19:06
Hi @AvePazuzu, no worries, no bother. So, you did install it via pip from GitHub, not from PyPI, right?

I can't reproduce here, it works for me. I just changed the version and pushed it. Can you pls try again and confirm `pip show openrouteservice` shows 
```yaml
Name: openrouteservice
Version: 1.0b0
```
If that's the case, pls post your raw request by passing `dry_run='true'` to the `distance_matrix` function, like 
> url:
>https://api.openrouteservice.org/matrix?profile=cycling->regular&api_key=key
>Parameters:
>{'headers': {'User-Agent': 'ORSClientPython.v0.4', 'Content-type': 'application/json'}, 'timeout': None, 
> 'json': {'locations': [[8.685551, 49.405724], [8.448486, 49.50381]], 'sources': 'all', 'destinations': 'all',     
> 'profile': 'cycling-regular', 'optimized': 'true'}}

**Comment by AvePazuzu** [comment] 2018-10-19 09:29
Hi @nilsnolde, 
what I did was to download the zip file with the 'openrouteservice-py-master'. In Anaconda Promt I navigated to the path and run:
`python setup.py install`
As last message I get: 
`Finished processing dependencies for openrouteservice==1.0b0`
But if I run: `pip show openrouteservice`
I get: 
```
Name: openrouteservice
Version: 0.4
```
Machine is running on Win7x64.

Regards!

**Comment by nilsnolde** [comment] 2018-10-19 10:16
That's clearly an environment issue. Pls read up on virtual environments and use them. They're the most important concept when using Python. 

I have no idea about your setup. But in a nutshell: `conda create --name ors-py python=3.6`, then activate the environment `conda activate ors-py` (or whatever that is in Win), ONLY then install ors-py via `pip install git+git://github.com/GIScience/openrouteservice-py` or via setup.py and conda.

**Comment by AvePazuzu** [comment] 2018-10-22 14:44
Hi @nilsnolde, 

thanks for the advice. It worked perfectly. 

Regards.

**Comment by nilsnolde** [comment] 2018-11-10 10:50
v1 is released with issue addressed

**Closed by nilsnolde** 2018-11-10 10:50 UTC
Labels: PyPI, has workaround
